@startuml diagAtividades-etapa3-componentes

skinparam linetype ortho
skinparam shadowing false
'skinparam monochrome true

skinparam activity {
  BackgroundColor #FFFFFF                      
  BorderColor      #0077b6                     
  FontColor        #000000                     
}

skinparam ActivityStartColor #0077b6
skinparam ActivityEndColor   #0077b6           
skinparam ArrowColor         #0077b6  

skinparam activityDiamondBackgroundColor #FFFFFF    
skinparam activityDiamondBorderColor     #0077b6

start

:Prompt para listar possíveis componentes (a partir do código PUML de casos de uso):\n"A partir do código PlantUML de casos de uso, liste os possíveis componentes\n(apenas nomes, sem código): <código final do caso de uso>";
while(Os componentes listados estão coesos?) is (Não)
  :Prompt para agrupar componentes semelhantes da lista anterior:\n"Agrupe componentes semelhantes e retorne uma nova lista";
endwhile (Sim)
:Prompt para gerar código PUML de componentes (baseado na listagem anterior):\n"Baseado da lista de componentes anterior e no código de casos de uso, gere um\ndiagrama de componentes em PUML contendo somente componentes (sem relações)";

while (Semântica de componentes mantida baseado no casos de uso?) is (Não)
  :Prompt corretivo único para heranças:\n"Implemente o componente X, respeitando a semântica de casos de uso";
endwhile (Sim)

while (Semântica dos relacionamentos mantida baseado no casos de uso?) is (Não)
  :Prompt para implementar relações de componentes:\n"Implemente as relações entre componentes no código PUML de componentes. As relações devem\nseguir exatamente a mesma semântica dos casos de uso";
endwhile (Sim)

stop
@enduml