@startuml componentes-biblioteca
title Sistema Biblioteca — Diagrama de Componentes

' Atores
actor "Usuário do Sistema" as UsuarioDoSistema
actor "Membro da comunidade USP" as MembroDaComunidadeUSP
actor "Bibliotecário" as Bibliotecario
actor "Administrador" as Administrador
actor "Sistema" as Sistema

' Relações entre atores (conforme diagrama de casos de uso)
MembroDaComunidadeUSP --|> UsuarioDoSistema
Bibliotecario --|> UsuarioDoSistema
Administrador --|> UsuarioDoSistema

' Componentes
component "gestão de reserva" as CGR
component "gestão de usuários" as CGU
component "gestão de equipamentos" as CGE
component "gestão de salas" as CGS
component "monitoramento do sistema" as CGMS
component "monitoramento & logs" as CGML

MembroDaComunidadeUSP --> CGU
MembroDaComunidadeUSP --> CGS
MembroDaComunidadeUSP --> CGE
MembroDaComunidadeUSP --> CGR

Bibliotecario --> CGS
Bibliotecario --> CGE
Bibliotecario --> CGR

Administrador --> CGU
Administrador --> CGMS

Sistema --> CGR
Sistema --> CGML
@enduml
