@startuml diagAtividades-etapa3-diagramaClasses
skinparam linetype ortho
skinparam shadowing false
'skinparam monochrome true

skinparam activity {
  BackgroundColor #FFFFFF                      
  BorderColor      #0077b6                     
  FontColor        #000000                     
}

skinparam ActivityStartColor #0077b6
skinparam ActivityEndColor   #0077b6           
skinparam ArrowColor         #0077b6  

skinparam activityDiamondBackgroundColor #FFFFFF    
skinparam activityDiamondBorderColor     #0077b6

start

:Prompt para implementar apenas as classes em código PUML:\n"Implemente apenas classes no código PUML de diagrama de classes,\nsem multiplicidades, relações, atributos e métodos. Faça a implementação\nbaseado no código de casos de uso. Código: <código do casos de uso>";
while (Todas as classes foram geradas?) is (Não)
    :Prompt corretivo único para gerar classe:\n"Gere a classe X, mantendo a semântica\n do código de componentes: <código de componentes>";
endwhile (Sim)
:Prompt para implementar apenas as heranças entre classes:\n"No código anterior, implemente apenas as relações de heranças\nque ocorrem entre as classes, considerando a semântica de casos de uso e componentes";
while (Heranças estão coerentes?) is (Não)
    :Prompt corretivo único para gerar herança:\n"Classe Y herda características da classe Z";
endwhile (Sim)
:Prompt para implementar apenas os relacionamentos e multiplicidades:\n"No código anterior, um representante de clube trabalha em um clube esportivo.\nUm patrocinador visualiza nenhuma ou várias postagens de um atleta.\nVários atletas...";
while (Relacionamentos e multiplicidades estão coerentes?) is (Não)
    :Prompt corretivo único para implementar relacionamento e multiplicidade:\n"<quantidade classe A> Classe A se relaciona com <quantidade classe B> classe B";
endwhile (Sim)
:Prompt para implementar apenas os atributos de cada classe, considerando características reais:\n"Implemente no código anterior apenas os atributos de cada classe, considerando características reais da classe";
while (Atributos de todas as classes estão coerentes?) is (Não)
    :Prompt corretivo único:\n"Implemente os atributos P, Q e R na classe C";
endwhile (Sim)

stop
@enduml