@startuml diagAtividades-Metodologia
!pragma useBetaStyle true
skinparam linetype ortho
skinparam shadowing false
skinparam monochrome true
top to bottom direction

<style>
activityDiagram {
  activity {
    RoundCorner 0
  }
}
</style>
skinparam Shadowing false

(*) --> "Etapa 1: Estudo do subprocesso de análise e projeto" as e1
e1  --> "Etapa 2: Exploração das diretrizes do LLM"           as e2
e2  --> "Etapa 3: Formalização das diretrizes"                as e3
e3  --> "Etapa 4: Avaliação das diretrizes"                            as e4

if Há novas diretrizes na etapa 4? then
  -->[Sim]  e3
else
  -->[Não] "Etapa 5: Avaliação e análise de similaridade entre diagramas"          as e5                        
endif

if "Há refinamentos na etapa 5?" then
  -->[Sim]  e3
else
  -->[Não](*)                        
endif
