@startuml diagAtividades-Metodologia
skinparam linetype ortho
skinparam shadowing false
skinparam monochrome true

<style>
activityDiagram {
  activity {
    RoundCorner 0
  }
}
</style>
skinparam Shadowing false

start
:Estudo do subprocesso de análise e projeto;
:Exploração das diretrizes do LLM;
note right
Testes de prompt em um sistema de software para avaliar as diretrizes do LLM.
end note
:Formalização das diretrizes;
:Avaliação das diretrizes;
note right
Aplicação das diretrizes em 4 sistemas, para geração de diagramas por meio de LLM.
end note
:Avaliação e análise de similaridade entre diagramas;
note right
Similaridade dos diagramas do LLM baseado em projetos de graduação.
end note
stop
@enduml
